include:
  - db/compose.yml

services:
  web:
    container_name: rag_poc_web
    build: ./web
    command: pnpm dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - web/.env.local
    networks:
      - internal
    volumes:  # avoid mounting node_modules
      - ./web/src:/usr/src/app/src
      - ./web/migrations:/usr/src/app/migrations
    stdin_open: true
    tty: true
