services:
  pg:
    build: ./pg
    environment:
      POSTGRES_DB: phi3rag
      POSTGRES_USER: phi3rag
      POSTGRES_PASSWORD: phi3password
    ports:
      - "5432:5432"
    volumes:
      - pg/data:/var/lib/postgresql/data
networks:
  internal:
    # let containers communicate with each other
    driver: bridge