services:

  pg:
    container_name: rag_poc_pg
    build: ./pg
    environment:
      - POSTGRES_DB=rag
      - POSTGRES_USER=rag
      - POSTGRES_PASSWORD=rag_password
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - ./pg/data:/var/lib/postgresql/data

networks:
  internal:
    # let containers communicate with each other
    driver: bridge